# **Project Title**


## **Aviation Customer Experience & Service Analytics**

# **Objective(Problem statment)**

1.   To identify meaningful patterns, trends, and insights in airline customer reviews using Exploratory Data Analysis (EDA).

2.   To clean, transform, and preprocess airline review data for reliable analysis.

1.   To analyze customer satisfaction based on overall ratings, service ratings, traveller types, seat types, airlines, and recommendation status.
2.   To identify which airline service areas such as seat comfort, cabin staff service, food and beverages, ground service, Wi-Fi connectivity, and in-flight entertainment contribute to customer experience.

1.   To create meaningful visualizations that clearly communicate trends and customer experience patterns.
2.   To provide actionable insights and recommendations that can help understand areas of strong and weak airline service performance.

## **Outcome**

The project will provide insights into airline customer satisfaction, service performance, recommendation patterns, and trends over time. The final analysis will provide evidence-based insights that can support better understanding of customer satisfaction and airline service performance.

## **Domain**

Aviation / Airline Customer Experience

## **Dataset Information**


**Dataset:** Skytrax Airline Review Data

**Original Source:** [Mendeley Data – Airline Travel Reviews Data (Skytrax)](https://data.mendeley.com/datasets/vgjk58vf8h/1)

**Original Dataset:** 64,740 rows × 19 columns

**Original Timeline:** 2015–2025

**Dataset Used for Analysis:** 21,984 rows × 19 columns

**Analysis Period:** 2021–2025

**Format:** CSV

The original Skytrax Airline Review Data contains 64,740 airline reviews covering 2015–2025. For this project, the dataset was filtered to include only reviews from 2021–2025, resulting in a working dataset of 21,984 records and 19 columns. The filtered dataset is stored in CSV format and is used for Python-based data cleaning, EDA, visualization, and subsequent Power BI analysis.

**Dataset Column / Features Description:**
- review_date – Date when the review was posted.
- over_all_rating – Overall customer rating from 1–10.
- review_header – Title of the customer review.
- trip_verified – Indicates whether the review is verified.
- review_text – Detailed customer feedback.
- aircraft – Aircraft information; will be removed due to high - missing values and inconsistent entries.
- type_of_traveller – Category of traveller.
- seat_type – Class/type of seat used.
- route – Flight travel route.
- date_flown – Date or period of the flight.
- seat_comfort – Rating for seat comfort.
- cabin_staff_service – Rating for cabin staff service.
- food__beverages – Rating for food and beverages.
- inflight_entertainment – Rating for in-flight entertainment.
- ground_service – Rating for ground services.
- wifi__connectivity – Rating for Wi-Fi/connectivity.
- value_for_money – Rating for value for money.
- recommended – Whether the customer recommends the airline.
- airline_name – Name of the reviewed airline.

# Stages for DA Project

## Stage 1 – Problem Definition and Dataset Selection


* **Business Problem and Expected Outcome**

The objective is to analyze airline customer reviews to understand customer satisfaction and identify the key service areas that influence the overall airline experience.

The analysis will help identify trends in customer ratings, service performance, and recommendation patterns, and provide insights into areas where airline services can be improved.

* **Dataset Selection**

The Skytrax Airline Review Data is selected for this project. It contains 64,740 airline customer reviews with 19 features, covering the period 2015–2025.

For this analysis, the 2021–2025 records will be considered to focus on recent customer experiences. The filtered working dataset contains 21,984 reviews and 19 columns. The dataset includes overall ratings, service ratings, traveller information, seat type, recommendation status, airline name, and customer review text.

* **Source:** [Mendeley Data – Airline Travel Reviews Data (Skytrax)](https://data.mendeley.com/datasets/vgjk58vf8h/1)

* **Importing libraries and loading dataset**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings("ignore")

In [8]:

url = "https://raw.githubusercontent.com/InfantaKennedy/DA-Main-Project---Aviation-Customer-Experience-Service-Analytics/refs/heads/main/Skytrax%20Airline%20Review%20Data(2021-2025)%20-%20Raw%20File.csv"

df = pd.read_csv(url)

* ## Initial EDA

In [6]:
# Dataset Preview:

df.head()

,review_date,over_all_rating,review_header,trip_verified,review_text,aircraft,type_of_traveller,seat_type,route,date_flown,seat_comfort,cabin_staff_service,food__beverages,inflight_entertainment,ground_service,wifi__connectivity,value_for_money,recommended,airline_name
0,2025-08-04,1,"""showed zero empathy for passengers""",Trip Verified,My afternoon flight was delayed and eventuall...,NaN,business,economy_class,dubai_to_kochi,august_2025,1.0,2.0,2.0,2.0,1.0,1.0,1.0,no,spicejet
1,2025-07-21,2,"""Extremely dissatisfied""",Trip Verified,The flight was postponed 3 times with insuffi...,NaN,family_leisure,economy_class,pune_to_dubai,july_2025,1.0,3.0,NaN,NaN,3.0,NaN,2.0,no,spicejet
2,2025-04-19,2,"""Very bad experience""",Trip Verified,They will charge you for your hand baggage if...,NaN,business,economy_class,mumbai_to_kolkata,april_2025,3.0,3.0,3.0,NaN,1.0,NaN,2.0,no,spicejet
3,2025-03-12,1,“What a difficult airline”,Trip Verified,The flight was delayed from 15:20 to 16:25. I...,NaN,business,economy_class,"pune,_india_to_new_delhi,_india",march_2025,3.0,4.0,NaN,NaN,5.0,NaN,1.0,no,spicejet
4,2025-03-02,2,“Poor chaotic boarding”,Trip Verified,No crowd control and boarding was like cattle...,boeing_747,solo_leisure,economy_class,mumbai_to_new_delhi,march_2025,3.0,1.0,3.0,NaN,1.0,NaN,2.0,no,spicejet

In [10]:
# Dataset Dimensions

df.shape

(21984, 19)

In [13]:
# Dataset Information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21984 entries, 0 to 21983
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   review_date             21984 non-null  object
 1   over_all_rating         21984 non-null  int64
 2   review_header           21984 non-null  object
 3   trip_verified           21957 non-null  object
 4   review_text             21871 non-null  object
 5   aircraft                6932 non-null   object
 6   type_of_traveller       21981 non-null  object
 7   seat_type               21983 non-null  object
 8   route                   21810 non-null  object
 9   date_flown              21981 non-null  object
 10  seat_comfort            20230 non-null  float64
 11  cabin_staff_service     20070 non-null  float64
 12  food__beverages         16368 non-null  float64
 13  inflight_entertainment  13828 non-null  float64
 14  ground_service          20975 non-null  float64
 15  wifi__connectivity      10568 non-null  float64
 16  value_for_money         21982 non-null  float64
 17  recommended             21983 non-null  object
 18  airline_name            21984 non-null  object
dtypes: float64(7), int64(1), object(11)
memory usage: 3.2+ MB

In [14]:
# Descriptive Statistics

df.describe()

,over_all_rating,seat_comfort,cabin_staff_service,food__beverages,inflight_entertainment,ground_service,wifi__connectivity,value_for_money
count,21984.000000,20230.000000,20070.000000,16368.000000,13828.000000,20975.000000,10568.000000,21982.000000
mean,3.295306,2.496639,2.745740,2.450513,2.491611,2.194136,2.066616,2.115640
std,3.205475,1.444052,1.592647,1.493349,1.497183,1.559712,1.452347,1.479368
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
50%,1.000000,2.000000,3.000000,2.000000,2.000000,1.000000,1.000000,1.000000
75%,5.000000,4.000000,4.000000,4.000000,4.000000,4.000000,3.000000,3.000000
max,10.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

In [15]:
# Missing Value Check

df.isnull().sum()

review_date                   0
over_all_rating               0
review_header                 0
trip_verified                27
review_text                 113
aircraft                  15052
type_of_traveller             3
seat_type                     1
route                       174
date_flown                    3
seat_comfort               1754
cabin_staff_service        1914
food__beverages            5616
inflight_entertainment     8156
ground_service             1009
wifi__connectivity        11416
value_for_money               2
recommended                   1
airline_name                  0
dtype: int64

In [16]:
# Duplicate Record Check

df.duplicated().sum()

np.int64(0)